# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSEQUOIA2DockWidget
                                 A QGIS plugin
 simplifions le qutodien des forestiers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Alexandre Le Bars - SequoiAPP
        email                : alexlb329@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# ==========================================================================
# region import
# ==========================================================================

# python 

import os

# Qgis

from qgis.PyQt import QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QWidget
from qgis.PyQt.QtCore import pyqtSignal
from PyQt5.QtGui import QIcon

# QSEQUOIA2

from qsequoia2.scripts.data_settings.add_data import AddDataDialog

from qsequoia2.scripts.LayoutDesigner.LayoutDesigner import LayoutDesignerDialog
from qsequoia2.scripts.forest_data.forest_data import ForestDataDialog
from qsequoia2.scripts.tools.tools import ToolsDialog
from .scripts.add_on.addon_loader import load_addons
from.scripts.utils.variable import get_global_variable

# import de l'UI

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'QSEQUOIA2_dockwidget_base.ui'))

# endregion

# ==========================================================================
# region Définition de la classe
# ==========================================================================

class QSEQUOIA2DockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, iface, current_project_name, current_style_folder, downloads_path, current_project_folder, parent=None):
        """Constructor."""
        super(QSEQUOIA2DockWidget, self).__init__(parent)
        self.iface = iface
        self.setupUi(self)
        self.project_name = current_project_name
        self.current_style_folder = current_style_folder
        self.downloads_path = downloads_path
        self.current_project_folder = current_project_folder

        # récupération de la variable du dossier des addons pour éviter le crash si inexistante

        self.addon_folder = get_global_variable("QS2_addon_folder")



        # chemin vers logo 
        plugin_dir = os.path.dirname(__file__)
        logo_path = os.path.join(plugin_dir, "icon.png")

        # définit l’icône du dockwidget
        self.setWindowIcon(QIcon(logo_path))

        # ---------------------------------------------------------------
        # import dans l'UI principale des différents modules de Qsequoia2
        # ---------------------------------------------------------------




        # -- Import du module LayoutDesigner --
        self.LayoutDesigner_tab = QWidget()
        self.LayoutDesigner_tab = LayoutDesignerDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, iface = self.iface)

        # -- Import du Module add_data --
        self.data_settings_tab = QWidget()
        self.data_settings_tab = AddDataDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, parent=self, iface=self.iface)

        # -- Import du module Tools_box --
        self.tools_tab = QWidget()
        self.tools_tab = ToolsDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, iface = self.iface)

        # -- Import du module forest_data --
        self.forest_data_tab = QWidget()
        self.forest_data_tab = ForestDataDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, iface = self.iface)


        # Ajoute des icons au QTabWidget

        plugin_path = os.path.dirname(__file__)
        self.tabWidget.addTab(self.LayoutDesigner_tab, QIcon(plugin_path + "/icons/LayoutDesigner.svg"),"")
        self.tabWidget.setTabToolTip(1, "Cartographie thématiques")
        self.tabWidget.addTab(self.forest_data_tab, QIcon(plugin_path + "/icons/forest_data.svg"),"")
        self.tabWidget.setTabToolTip(2, "Metadata sur la propriété")
        self.tabWidget.addTab(self.data_settings_tab, QIcon(plugin_path + "/icons/add_data.svg"),"")
        self.tabWidget.setTabToolTip(3, "Ajout de données")
        self.tabWidget.addTab(self.tools_tab, QIcon(plugin_path + "/icons/tools.svg"),"")
        self.tabWidget.setTabToolTip(0, "Outils et fonctions")

        # Import des addons
        if self.addon_folder:
            load_addons(plugin = self, current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, iface = self.iface)
        


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    


