# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSEQUOIA2DockWidget
                                 A QGIS plugin
 simplifions le qutodien des forestiers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-07
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Alexandre Le Bars - SequoiAPP
        email                : alexlb329@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QWidget
from qgis.PyQt.QtCore import pyqtSignal
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.PyQt.QtWidgets import QTreeWidgetItem
from PyQt5.QtGui import QIcon

from qsequoia2.scripts.data_settings.add_data import AddDataDialog
from qsequoia2.scripts.forest_settings.forest_settings_dialog import Ui_ForestSettingsDialog
from qsequoia2.scripts.project_settings.project_settings_dialog import Ui_ProjectSettingsDialog
from qsequoia2.scripts.project_settings.project_settings import ProjectSettingsDialog
from qsequoia2.scripts.data_settings.add_data_dialog import Ui_AddDataDialog
from qsequoia2.scripts.tools_settings.tools_settings_dialog import Ui_ToolsSettingsDialog
from qsequoia2.scripts.tools_settings.tools_settings import ToolsSettingsDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'QSEQUOIA2_dockwidget_base.ui'))


class QSEQUOIA2DockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, iface, current_project_name, current_style_folder, downloads_path, current_project_folder, parent=None):
        """Constructor."""
        super(QSEQUOIA2DockWidget, self).__init__(parent)
        self.iface = iface
        self.setupUi(self)
        self.project_name = current_project_name
        self.current_style_folder = current_style_folder
        self.downloads_path = downloads_path
        self.current_project_folder = current_project_folder



        # chemin vers logo 
        plugin_dir = os.path.dirname(__file__)
        logo_path = os.path.join(plugin_dir, "icon.png")

        # définit l’icône du dockwidget
        self.setWindowIcon(QIcon(logo_path))

        # ---------------------------------------------------------------
        # import dans l'UI principale des différents modules de Qsequoia2
        # ---------------------------------------------------------------


        # -- Import du module Tools_box --
        self.tools_tab = QWidget()
        self.tools_ui = Ui_ToolsSettingsDialog()
        self.tools_ui.setupUi(self.tools_tab)
        self.tools_tab = ToolsSettingsDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, iface = self.iface)

        # -- Import du module forest_settings --
        forest_settings_tab = QWidget()
        self.forest_settings_ui = Ui_ForestSettingsDialog()
        self.forest_settings_ui.setupUi(forest_settings_tab)

        # -- Import du module project_settings --
        self.project_settings_tab = QWidget()
        self.project_settings_tab = ProjectSettingsDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, iface = self.iface)

        # -- Import du Module add_data --
        self.data_settings_tab = QWidget()
        self.data_settings_tab = AddDataDialog(current_project_name=self.project_name, current_style_folder=self.current_style_folder, downloads_path=self.downloads_path, current_project_folder=self.current_project_folder, parent=self, iface=self.iface)


        # Ajoute des icons au QTabWidget

        plugin_path = os.path.dirname(__file__)
        self.tabWidget.addTab(self.tools_tab, QIcon(plugin_path + "/icons/tools_settings.svg"),"")
        self.tabWidget.setTabToolTip(0, "Outils et fonctions")
        self.tabWidget.addTab(self.project_settings_tab, QIcon(plugin_path + "/icons/project_settings.svg"),"")
        self.tabWidget.setTabToolTip(1, "Cartographie")
        self.tabWidget.addTab(forest_settings_tab, QIcon(plugin_path + "/icons/forest_settings.svg"),"")
        self.tabWidget.setTabToolTip(2, "Paramètre de la propriété")
        self.tabWidget.addTab(self.data_settings_tab, QIcon(plugin_path + "/icons/add_data.svg"),"")
        self.tabWidget.setTabToolTip(3, "Ajout de données")



    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()

    


