"""
/***************************************************************************
 {{ADDON_NAME}}
                                 A QSEQUOIA2 ADD-ON

 Generated by QSEQUOIA2
                             -------------------

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
SequoiAPP(Qsequoia2)
"""

# ==============================================================
# region import
# ==============================================================

# Python

from importlib.util import module_from_spec, spec_from_file_location

import yaml, importlib
from pathlib import Path

#QGIS
from PyQt5.QtWidgets import QWidget, QLabel, QVBoxLayout, QDialog
from qgis.core import QgsApplication
from PyQt5 import uic

#  constantes
FORM_CLASS, _ = uic.loadUiType(
    Path(__file__).parent / f"{{ADDON_NAME}}.ui")

ADDON_PATH = Path(__file__).parent
ADDON_FUNCTIONS_REGISTRY = Path(ADDON_PATH / "functions.yaml")
PROFILE_PATH = QgsApplication.qgisSettingsDirPath()
QS2_PATH = Path(PROFILE_PATH) / "python" / "plugins" / "qsequoia2"
QS2_CONFIG_PATH = QS2_PATH / "config"
QS2_FONCTIONS_REGISTRY = QS2_CONFIG_PATH / "QS2_functions_registry.yaml"

# ==============================================================
# region initialisation de {{ADDON_NAME}}
# ==============================================================

class {{ADDON_CLASS}}(QDialog, FORM_CLASS):
    """Initialise le module, récupère et expose une UI"""

    # modification dans cette region à vos risques et périls ! 

    def __init__(self, plugin, iface, parent=None, **kwargs):
        """Récupère les variables de Qsequoia et leurs configs"""

        # Charge l'UI
        super().__init__(parent)
        self.setupUi(self)

        # Récupère les paramètres de la classe Qsequoia2 principale
        self.plugin = plugin
        self.iface = iface

        # -- récupère la liste des fonctions --

        # Charger dynamiquement les fonctions
        self.qs2 = self._functions_loader(yaml_path=ADDON_FUNCTIONS_REGISTRY)# fonctions QSequoia2

        # Vous pouvez décrire vos fonctions dans le YAML functions, elles seront importées via la fonction suivante

        self.adn = self._functions_loader(yaml_path=QS2_FONCTIONS_REGISTRY)# fonction interne de l'addon

        # Bouton test

        self.pushButton.clicked.connect(self.print_variables)
        
    def _functions_loader(self, yaml_path):
        FUNCTIONS = {}

        with open(yaml_path, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)

        for func_name, entry in config.items():

            module_path = entry.get("path")
            attr_name = entry.get("name")
            args = entry.get("args", [])

            if not module_path or not attr_name:
                raise ValueError(f"Entrée YAML invalide : {func_name}")

            # Import dynamique du module
            module = importlib.import_module(module_path)

            # Récupération de la fonction ou classe
            obj = getattr(module, attr_name)

            # Création d’un wrapper si des arguments doivent être injectés
            if args:
                def make_wrapper(obj, args):
                    def wrapper(*_unused, **_unused_kw):
                        resolved_args = []
                        for a in args:
                            if a == "self":
                                resolved_args.append(self)
                            else:
                                resolved_args.append(getattr(self, a, a))
                        return obj(*resolved_args)
                    return wrapper

                wrapped = make_wrapper(obj, args)
                setattr(self, func_name, wrapped)
                FUNCTIONS[func_name] = wrapped

            else:
                setattr(self, func_name, obj)
                FUNCTIONS[func_name] = obj

        return FUNCTIONS
        

    # --- Méthodes pour QTabWidget ---

    def get_name(self):
        return "{{ADDON_NAME}}"

    def get_tab(self):
        return self
    
    # ===============================================================
    # region c'est à vous !
    # ===============================================================

    # Vous êtes désormais libre mais : 
    # !! Ne pas sortir de la classe !!

    # --- Méthode de test et demo ---

    def print_variables(self):
        print("nom de projet:", self.project_name)
        print("dossier de projet:", self.project_folder)
        print("dossier de style :", self.style_folder)
        print("dossier de téléchargement :", self.downloads_path)
        # exemple de test d'appel de fonctions Qsequoia2
        args = "Bonjour !" 

        # ou pf indique l'appel direct d'une fonction plugin
        self.pf.messageBar(self.iface, "Salut, ceci est une fonction Qsequoia2 !", "s",10) # Appel de la fonction Qsequoia2
        
        # l'utilisation des fonctions Qsequoia2 est possible dans un script externe de manière classique
        # mais en passant toujours  : pf : comme argument dans la fonction d'appel 
        # par exemple : 

        self.af.PluginExemple(pf=self.pf, self=self,iface = self.iface,args=args) # exemple renvoie vers la fonction test.

        # L'appel des fonctions internes de l'addon peuvent s'appeler de cette manière

        self.af.AddonExemple(self= self, iface= self.iface, args=args)
        



    
    # endregion