"""
/***************************************************************************
 {{ADDON_NAME}}
                                 A QSEQUOIA2 ADD-ON

 Generated by QSEQUOIA2
                             -------------------

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 Alexandre Le Bars - comité des forêts 2026  - SequoiAPP(Qsequoia2)
"""

# ==============================================================
# region import
# ==============================================================

# Python
import os, yaml, importlib
from types import SimpleNamespace

#QGIS
from PyQt5.QtWidgets import QWidget, QLabel, QVBoxLayout, QDialog
from qgis.core import QgsApplication
from PyQt5 import uic

#UI
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "{{ADDON_NAME}}.ui"))


# ==============================================================
# region chargement des fonctions qsequoia2
# ==============================================================

class PluginFunctionLoader:
    """Charge les fonctions de Qseuoia2 et interne à l'addon depuis un YAML et expose chaque fonction comme attribut"""
    def __init__(self, yaml_path):
        self._functions = {}
        with open(yaml_path, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)

        for name, info in config.items():
            module = importlib.import_module(info["path"])
            func = getattr(module, info["function"])
            setattr(self, name, func)  # rend accessible via self.""
            self._functions[name] = func

# ==============================================================
# region chargement des fonctions interne à {{ADDON_NAME}}
# ==============================================================

class AddonFunctionLoader:
    """Charge les fonctions internes de l'addon"""

    def __init__(self, addonFunction_yaml):

        self._functions = {}

        addon_path = os.path.dirname(addonFunction_yaml)

        with open(addonFunction_yaml, "r", encoding="utf-8") as f:
            config = yaml.safe_load(f)

        for name, info in config.items():

            script_path = os.path.join(addon_path, info["script"])
            func_name = info["function"]

            module_name = os.path.splitext(os.path.basename(script_path))[0]

            spec = importlib.util.spec_from_file_location(module_name, script_path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            func = getattr(module, func_name)

            setattr(self, name, func)
            self._functions[name] = func


        
#endregion
# ==============================================================
# region initialisation de {{ADDON_NAME}}
# ==============================================================

class {{ADDON_CLASS}}(QDialog, FORM_CLASS):
    """Initialise le module, récupère et expose une UI"""

    # modification dans cette region à vos risques et périls ! 

    def __init__(self, plugin, iface, parent=None, **kwargs):
        """Récupère les variables de Qsequoia et leurs configs"""

        # Charge l'UI
        super().__init__(parent)
        self.setupUi(self)

        # Récupère les paramètres de la classe Qsequoia2 principale
        self.plugin = plugin
        self.iface = iface

        # Récupère et expose le chemin de l'addon 
        self.addon_path = os.path.dirname(__file__)

        # Récupère et expose le chemin vers le plugin
        profile_path = QgsApplication.qgisSettingsDirPath()
        self.QS2_path = os.path.join(profile_path, "python", "plugins","qsequoia2") # Issu du dossier Qgis

        # Récupère et expose les fichiers de config de QS2 
        self.QS2_config_path = os.path.join(self.QS2_path, "inst") # Dossier inst mis à jour à chque chargement du plugin ! 

        # -- récupère la liste des fonctions --

        # Chemin vers le YAML du plugin
        self.Pluginfunctions_yaml = os.path.join(self.QS2_config_path,"QS2_functions.yaml")

        # Chemin vers le Yaml de {{ADDON_NAME}}
        self.addonFunction_yaml = os.path.join(self.addon_path, "_functions.yaml")


        # Charger dynamiquement les fonctions
        self.pf = PluginFunctionLoader(self.Pluginfunctions_yaml)# fonctions QSequoia2
        # Vous pouvez décrire vos fonctions dans le YAML _functions, elles seront importées via la fonction suivante
        self.af = AddonFunctionLoader(self.addonFunction_yaml) # fonction interne de l'addon

        # Bouton test
        self.pushButton.clicked.connect(self.print_variables)

    # --- Récupèration des variables de Qsequoia2 ---

    @property
    def project_name(self):
        return getattr(self.plugin, "current_project_name", None)

    @property
    def project_folder(self):
        return getattr(self.plugin, "current_project_folder", None)

    @property
    def style_folder(self):
        return getattr(self.plugin, "current_style_folder", None)

    @property
    def downloads_path(self):
        return getattr(self.plugin, "downloads_path", None)
    
    # --- Méthodes pour QTabWidget ---

    def get_name(self):
        return "{{ADDON_NAME}}"

    def get_tab(self):
        return self
    
    # ===============================================================
    # region c'est à vous !
    # ===============================================================

    # Vous êtes désormais libre mais : 
    # !! Ne pas sortir de la classe !!

    # --- Méthode de test et demo ---

    def print_variables(self):
        print("nom de projet:", self.project_name)
        print("dossier de projet:", self.project_folder)
        print("dossier de style :", self.style_folder)
        print("dossier de téléchargement :", self.downloads_path)
        # exemple de test d'appel de fonctions Qsequoia2
        args = "Bonjour !" 

        # ou pf indique l'appel direct d'une fonction plugin
        self.pf.test(self,self.iface,args) # Appel de la fonction Qsequoia2
        
        # l'utilisation des fonctions Qsequoia2 est possible dans un script externe de manière classique
        # mais en passant toujours  : pf : comme argument dans la fonction d'appel 
        # par exemple : 

        self.af.PluginExemple(pf=self.pf, self=self,iface = self.iface,args=args) # exemple renvoie vers la fonction test.

        # L'appel des fonctions internes de l'addon peuvent s'appeler de cette manière

        self.af.AddonExemple(self= self, iface= self.iface, args=args)
        



    
    # endregion