# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-ltr\python\plugins\Qsequoia2\dialogs\project_settings\project_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, yaml
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtCore import Qt, QTimer
from qgis.PyQt.QtWidgets import QWidget, QVBoxLayout, QTreeWidget, QTreeWidgetItem


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'project_settings.ui'))

class Ui_ProjectSettingsDialog(FORM_CLASS):
    def setupUi(self, ProjectSettingsDialog):
        super().setupUi(ProjectSettingsDialog)
        ProjectSettingsDialog.setObjectName("ProjectSettingsDialog")
