# Ce fichier est généré automatiquement par func_doc. Ne pas modifier manuellement.

main:
  type: function
  path: qsequoia2.plugin_upload
  name: main
  args:
  - parameters
  - arguments
hide_password:
  type: function
  path: qsequoia2.plugin_upload
  name: hide_password
  args:
  - url
  - start
Qsequoia2:
  type: class
  path: qsequoia2.qsequoia2
  name: Qsequoia2
SeqDirState:
  type: class
  path: qsequoia2.qsequoia2_dockwidget
  name: SeqDirState
Qsequoia2DockWidget:
  type: class
  path: qsequoia2.qsequoia2_dockwidget
  name: Qsequoia2DockWidget
qInitResources:
  type: function
  path: qsequoia2.resources
  name: qInitResources
  args: []
qCleanupResources:
  type: function
  path: qsequoia2.resources
  name: qCleanupResources
  args: []
load_actions:
  type: function
  path: qsequoia2.actions.registry
  name: load_actions
  args: []
AddDataTabWidget:
  type: class
  path: qsequoia2.modules.add_data.add_data
  name: AddDataTabWidget
on_new_addon_clicked:
  type: function
  path: qsequoia2.modules.add_on.addon_creator
  name: on_new_addon_clicked
  args:
  - iface
  - addons_dir
  - plugin
copy_addon_template:
  type: function
  path: qsequoia2.modules.add_on.addon_creator
  name: copy_addon_template
  args:
  - addon_name
  - addons_dir
create_addon_class:
  type: function
  path: qsequoia2.modules.add_on.addon_creator
  name: create_addon_class
  args:
  - addon_name
process_addon:
  type: function
  path: qsequoia2.modules.add_on.addon_creator
  name: process_addon
  args:
  - addon_dir
  - addon_name
  - addon_class
load_addons:
  type: function
  path: qsequoia2.modules.add_on.addon_loader
  name: load_addons
  args:
  - plugin
  - iface
test:
  type: function
  path: qsequoia2.modules.add_on.test
  name: test
  args:
  - self
  - iface
  - args
ForestType:
  type: class
  path: qsequoia2.modules.forest_data.forest_data
  name: ForestType
ForestDataWidget:
  type: class
  path: qsequoia2.modules.forest_data.forest_data
  name: ForestDataWidget
ForestMetadataBuilder:
  type: class
  path: qsequoia2.modules.forest_data.forest_metadata_builder
  name: ForestMetadataBuilder
update_forest_name:
  type: function
  path: qsequoia2.modules.forest_data.update_forest_name
  name: update_forest_name
  args:
  - prefix
  - seq_identifier
GlobalSettingsDialog:
  type: class
  path: qsequoia2.modules.global_settings.global_settings
  name: GlobalSettingsDialog
open_maps:
  type: function
  path: qsequoia2.modules.global_settings.go_to_maps
  name: open_maps
  args:
  - adress
LayoutBuilder:
  type: class
  path: qsequoia2.modules.layout_designer.layout_builder
  name: LayoutBuilder
LayoutDesignerWidget:
  type: class
  path: qsequoia2.modules.layout_designer.layout_designer
  name: LayoutDesignerWidget
buffer:
  type: function
  path: qsequoia2.modules.layout_designer.processing
  name: buffer
  args:
  - layer
  - distance
  - dissolve
  - segments
multipart_to_singleparts:
  type: function
  path: qsequoia2.modules.layout_designer.processing
  name: multipart_to_singleparts
  args:
  - layer
BuildContext:
  type: class
  path: qsequoia2.modules.layout_designer.project_builder
  name: BuildContext
ProjectBuilder:
  type: class
  path: qsequoia2.modules.layout_designer.project_builder
  name: ProjectBuilder
ProjectCanvas:
  type: class
  path: qsequoia2.modules.layout_designer.project_config_loader
  name: ProjectCanvas
LayoutMap:
  type: class
  path: qsequoia2.modules.layout_designer.project_config_loader
  name: LayoutMap
LegendSpec:
  type: class
  path: qsequoia2.modules.layout_designer.project_config_loader
  name: LegendSpec
ProjectLayout:
  type: class
  path: qsequoia2.modules.layout_designer.project_config_loader
  name: ProjectLayout
ProjectConfigLoader:
  type: class
  path: qsequoia2.modules.layout_designer.project_config_loader
  name: ProjectConfigLoader
getFinaldata:
  type: function
  path: qsequoia2.modules.table_check.data_table
  name: getFinaldata
  args:
  - synthese
sspf_surface_calculation:
  type: function
  path: qsequoia2.modules.table_check.data_table
  name: sspf_surface_calculation
  args:
  - ua_layer
table_check:
  type: class
  path: qsequoia2.modules.table_check.table_check
  name: table_check
ToolsDialog:
  type: class
  path: qsequoia2.modules.tools.tools
  name: ToolsDialog
get_alias_config_path:
  type: function
  path: qsequoia2.modules.utils.alias
  name: get_alias_config_path
  args: []
get_alias_config:
  type: function
  path: qsequoia2.modules.utils.alias
  name: get_alias_config
  args: []
get_alias:
  type: function
  path: qsequoia2.modules.utils.alias
  name: get_alias
  args:
  - key
configure_snapping:
  type: function
  path: qsequoia2.modules.utils.configure_snapping
  name: configure_snapping
  args: []
disabled_v_external_grass:
  type: function
  path: qsequoia2.modules.utils.disabled_v_external_grass
  name: disabled_v_external_grass
  args:
  - iface
get_group:
  type: function
  path: qsequoia2.modules.utils.layer_tree
  name: get_group
  args:
  - name
  - project
open_seq_dir:
  type: function
  path: qsequoia2.modules.utils.open_seq_dir
  name: open_seq_dir
  args:
  - project_folder
restore_qs2_project_variables:
  type: function
  path: qsequoia2.modules.utils.qgz_project
  name: restore_qs2_project_variables
  args:
  - variables
load_project:
  type: function
  path: qsequoia2.modules.utils.qgz_project
  name: load_project
  args:
  - project
  - path
  - variables
find_seq_project:
  type: function
  path: qsequoia2.modules.utils.qgz_project
  name: find_seq_project
  args:
  - seq_id
  - seq_dir
  - suffix
confirm_project_close:
  type: function
  path: qsequoia2.modules.utils.qgz_project
  name: confirm_project_close
  args:
  - project
  - iface
new_seq_project:
  type: function
  path: qsequoia2.modules.utils.qgz_project
  name: new_seq_project
  args:
  - project
  - iface
  - path
  - datum
  - ask
  - variables
open_seq_project:
  type: function
  path: qsequoia2.modules.utils.qgz_project
  name: open_seq_project
  args:
  - project
  - iface
  - seq_id
  - seq_dir
  - suffix
  - ask_unsaved
  - ask_create
  - preserve_qs2_variables
messageBar:
  type: function
  path: qsequoia2.modules.utils.Qmessage
  name: messageBar
  args:
  - iface
  - text
  - level
  - duration
messageLog:
  type: function
  path: qsequoia2.modules.utils.Qmessage
  name: messageLog
  args:
  - text
  - level
reloadQS2:
  type: function
  path: qsequoia2.modules.utils.reloader
  name: reloadQS2
  args:
  - plugin
  - plug
sync_seq_configs:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: sync_seq_configs
  args:
  - timeout
get_seq_config_path:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: get_seq_config_path
  args:
  - name
get_seq_config:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: get_seq_config
  args:
  - name
seq_key:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: seq_key
  args:
  - key
seq_layer:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: seq_layer
  args:
  - key
resolve_seq_layer:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: resolve_seq_layer
  args:
  - key
  - project
  - seq_id
seq_field:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: seq_field
  args:
  - field
get_style:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: get_style
  args:
  - layer_key
  - style_folder
_norm_project_path:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: _norm_project_path
  args:
  - raw_path
  - project
_vector_file_path:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: _vector_file_path
  args:
  - layer
  - project
_raster_file_path:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: _raster_file_path
  args:
  - layer
  - project
_find_existing_seq_layer:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: _find_existing_seq_layer
  args:
  - path
  - layer_type
  - group
seq_read:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: seq_read
  args:
  - key
  - seq_dir
  - add_to_project
  - group
  - style_folder
find_all_seq_dir:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: find_all_seq_dir
  args:
  - root_dir
  - max_dirs
find_seq_id:
  type: function
  path: qsequoia2.modules.utils.seq_config
  name: find_seq_id
  args:
  - seq_dir
get_tms_config_path:
  type: function
  path: qsequoia2.modules.utils.tms
  name: get_tms_config_path
  args: []
get_tms_config:
  type: function
  path: qsequoia2.modules.utils.tms
  name: get_tms_config
  args: []
tms_layer:
  type: function
  path: qsequoia2.modules.utils.tms
  name: tms_layer
  args:
  - key
_build_uri:
  type: function
  path: qsequoia2.modules.utils.tms
  name: _build_uri
  args:
  - url
  - style
_find_existing_tms:
  type: function
  path: qsequoia2.modules.utils.tms
  name: _find_existing_tms
  args:
  - source
  - group
tms_read:
  type: function
  path: qsequoia2.modules.utils.tms
  name: tms_read
  args:
  - key
  - group
  - load_style
get_global_variable:
  type: function
  path: qsequoia2.modules.utils.variable
  name: get_global_variable
  args:
  - name
set_global_variable:
  type: function
  path: qsequoia2.modules.utils.variable
  name: set_global_variable
  args:
  - name
  - value
get_project_variable:
  type: function
  path: qsequoia2.modules.utils.variable
  name: get_project_variable
  args:
  - name
set_project_variable:
  type: function
  path: qsequoia2.modules.utils.variable
  name: set_project_variable
  args:
  - name
  - value
get_qs2_project_variables:
  type: function
  path: qsequoia2.modules.utils.variable
  name: get_qs2_project_variables
  args:
  - project
_safe_set:
  type: function
  path: qsequoia2.modules.utils.variable
  name: _safe_set
  args:
  - setter
  - name
  - value
get_wmts_config_path:
  type: function
  path: qsequoia2.modules.utils.wmts
  name: get_wmts_config_path
  args: []
get_wmts_config:
  type: function
  path: qsequoia2.modules.utils.wmts
  name: get_wmts_config
  args: []
wmts_layer:
  type: function
  path: qsequoia2.modules.utils.wmts
  name: wmts_layer
  args:
  - key
_find_existing_wmts:
  type: function
  path: qsequoia2.modules.utils.wmts
  name: _find_existing_wmts
  args:
  - source
  - group
wmts_read:
  type: function
  path: qsequoia2.modules.utils.wmts
  name: wmts_read
  args:
  - key
  - group
PluginExemple:
  type: function
  path: qsequoia2.modules.add_on.templates.basic_addon.python.exemple
  name: PluginExemple
  args:
  - pf
  - self
  - iface
  - args
AddonExemple:
  type: function
  path: qsequoia2.modules.add_on.templates.basic_addon.python.exemple
  name: AddonExemple
  args:
  - self
  - iface
  - args
