assemblage:
  alias : "Plan d'assemblage cadastral"
  canvas:
    scale: 7500
    zoom_on: SEQ_PARCA_poly
    readonly: [SEQ_PARCA_poly]
    groups:
      - name: VECTEUR
        type: vector
        layers: &assemblage_w_vect 
          - COMS_TOPO_line
          - CURVES_line
          - COMS_TOPO_point
          - INFRA_point
          - INFRA_line
          - INFRA_poly
          - TOPONYME_point
          - ROAD_TOPO_line
          - ROAD_TOPO_poly
          - ROAD_GRAPH_line
          - ROAD_GRAPH_poly
          - HYDRO_poly
          - HYDRO_line
          - VEGE_poly
          - CAD_PARCELLE_poly
      - name: SEQUOIA
        type: vector
        layers: &assemblage_w_seq
          - SEQ_OWNER_line
          - SEQ_PARCA_poly

      - name: WMTS
        type: wmts
        layers: &assemblage_w_wmts
          - wmts_scan25_grey
          - wmts_scan100
          - wmts_scan1000
          - wmts_pci
          - wmts_irc
          - wmts_rgb
    themes:
      - name: assemblage
        show: [*assemblage_w_vect, *assemblage_w_seq]
      - name: assemblage+WMTS
        show: [*assemblage_w_vect, *assemblage_w_seq, *assemblage_w_wmts]

  
  layout:
    theme: 'assemblage'
    legends:
      - name: legend1
        layers: [*assemblage_w_seq, *assemblage_w_wmts]
      - name: 'legend2'
        layers: *assemblage_w_vect

situation:
  alias : "Cartographie de situation"
  canvas:
    scale: 25000
    zoom_on: 'SEQ_PARCA_poly'
    readonly: ['SEQ_PARCA_poly']
    groups: 
      - name: VECTEUR
        type: vector
        layers: &situation_w_vect
          - COMS_TOPO_line
          - CURVES_line
          - PRSF_point
          - INFRA_poly
          - ROAD_TOPO_poly
          - ROAD_TOPO_line
          - TOPONYME_point
          - HYDRO_poly
          - HYDRO_line
          - VEGE_poly

      - name: SEQUOIA
        type: vector
        layers: &situation_w_seq
          - SEQ_PF_point
          - SEQ_PF_line
          - SEQ_PF_poly
          - SEQ_PROP_point

      - name: WMTS
        type: wmts
        layers: &situation_w_wmts
          - 'wmts_scan25'
          - 'wmts_scan1000'

    themes:
      - name: situation1/25000
        show: [*situation_w_vect, *situation_w_seq]
      - name: situation1/25000+WMTS
        show: [*situation_w_seq, *situation_w_wmts]
      - name: situation1/100000
        show: ['SEQ_PROP_point', 'wmts_scan1000']

  layout:
    theme: 'situation1/25000'
    legends:
      - name: legend1
        layers: [*situation_w_seq,'wmts_scan1000']
      - name: legend2
        layers: *situation_w_vect

peuplements:
  alias : "Cartographie des peuplements forestiers"
  canvas:
    scale: 7500
    zoom_on: 'parca_polygon_lgd_peuplements'
    readonly: [parca_polygon_lgd_peuplements, parca_polygon_occup, ua_polygon_plt]
    groups:
      - name: LEGEND
        type: vector
        layers: ['parca_polygon_lgd_peuplements']
      - name: VECTEUR
        type: vector
        layers: &peuplements_w_vect ['com_line', 'com_point', 'infra_point_peuplements', 'infra_line', 'topo_line', 'infra_polygon', 'lieudit_point', 'road_line', 'road_polygon', 'route_line', 'route_polygon']
      - name: SEQUOIA
        type: vector
        layers: &peuplements_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'sspf_polygon', 'sspf_polygon_plt', 'parca_polygon_occup', 'ua_polygon', 'ua_polygon_plt', 'ua_polygon_ame']
      - name: WMTS
        type: wmts
        layers: &peuplements_w_wmts ['wmts_scan25_grey', 'wmts_scan100', 'wmts_scan1000', 'wmts_pci', 'wmts_irc', 'wmts_rgb']

    themes:
      - name: peuplements
        show: [*peuplements_w_vect, *peuplements_w_seq]
      - name: peuplements+WMTS
        show: [*peuplements_w_vect, *peuplements_w_seq, *peuplements_w_wmts]


  layout:
    theme: 'peuplements'
    legends:
      - name: legend1
        layers: ['SEQ_SSPF_poly']
      - name: legend2
        layers: ['sspf_polygon_plt']

enjeux_environnementaux:
  alias : "Cartographie des enjeux environnementaux"
  canvas:
    scale: 15000
    zoom_on: SEQ_PARCA_poly
    readonly: [SEQ_PARCA_poly]

    groups:
      - name : SEQUOIA
        type : vector
        layers : &enjeux_env_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'pnr', 'znieff1', 'znieff2', 'zico', 'pn', 'sic', 'zps', 'ramsar', 'bios']
      - name : WMTS
        type : wmts
        layers : &enjeux_env_w_wmts ['wmts_scan25_grey']

    themes:
      - name: environnement
        show: [*enjeux_env_w_seq, *enjeux_env_w_wmts]

  layout:
    theme: 'environnement'
    legends:
      - name: legend1
        layers: ['SEQ_PARCA_poly']
      - name: legend2
        layers: ['prop_line', 'pf_line', 'pf_polygon', 'pnr', 'znieff1', 'znieff2', 'zico', 'pn', 'sic', 'zps', 'ramsar', 'bios']

enjeux_sociaux:
  alias : "Cartographie des enjeux sociaux"
  canvas:
    scale: 15000
    zoom_on: SEQ_PARCA_poly
    readonly: [SEQ_PARCA_poly]
    groups:
      - name : LEGEND
        type : vector
        layers : [SEQ_PARCA_poly]
      - name : SEQUOIA
        type : vector
        layers : &enjeux_sociaux_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'ppi', 'ppr', 'ppe']
      - name : WMTS
        type : wmts
        layers : &enjeux_sociaux_w_wmts ['wmts_scan25_grey']

    themes:
      - name: social
        show: [*enjeux_sociaux_w_seq, *enjeux_sociaux_w_wmts]

  layout:
    theme: 'social'
    legends:
      - name: legend1
        layers: ['SEQ_PARCA_poly']
      - name: legend2
        layers: ['ppi', 'ppr', 'ppe']

enjeux_patrimoniaux:
  alias : "Cartographie des enjeux patrimoniaux"
  canvas:
    scale: 15000
    zoom_on: SEQ_PARCA_poly
    readonly: [SEQ_PARCA_poly]

    groups:
      - name : LEGEND
        type : vector
        layers : ['SEQ_PARCA_poly']
      - name : SEQUOIA
        type : vector
        layers : &enjeux_pat_w_seq ['prop_line', 'pf_line', 'pf_polygon', 'mh', 'ppmh', 'site']
      - name : WMTS
        type : wmts
        layers : &enjeux_pat_w_wmts ['wmts_scan25_grey']
    themes:
      - name: patrimoine
        show: [*enjeux_pat_w_seq, *enjeux_pat_w_wmts]

  layout:
    theme: 'patrimoine'
    legends:
      - name: legend1
        layers: ['SEQ_PARCA_poly']
      - name: legend2
        layers: ['mh', 'ppmh', 'site']

geologie:
  alias : "Cartographie géologique et stationnelle"
  canvas:
    scale: 15000
    zoom_on: SEQ_PARCA_poly
    readonly: [SEQ_PARCA_poly]

    groups:
      - name : SEQUOIA
        type : vector
        layers : &geol_w_seq ['SEQ_OWNER_line', 'SEQ_PF_line']

      - name : VECTOR
        type : vector
        layers : &geol_w_vect ['CURVES_line','SOL_BDCHARM50_poly','SOL_CARHAB_poly']
      - name : WMTS
        type : wmts
        layers : &geol_w_wmts ['wmts_scan25_grey']
    themes:
      - name: geologie
        show: [*geol_w_seq, *geol_w_vect, *geol_w_wmts]

  layout:
    theme: 'geologie'
    legends:
      - name: legend1
        layers: ['SEQ_PARCA_poly']
      - name: legend2
        layers: ['SOL_BDCHARM50_poly', 'SOL_CARHAB_poly']